# These are supported funding model platforms
Solana (SOL)
Address: FpRsCX7cYGWzD68CpaTTpin5zjG9edJEGdZBPUGqHXpY

Ethereum (ETH)
Address: 0x241b7Eeb3780AC0D91924620F0DD1Fa0aaF6AD40

Dogecoin (DOGE)
Address: xpub6CwV8pWTKSzkP97AyYM7pih1D8wa9GwoaNA81D63PL5Ga3eLmNhnFr8VfcCP2mTKW1H3Q19RRzv7fwHXFaW3Dog9t9MShtUJ1pQRK3Soww4

Litecoin (LTC)
Address: xpub6CpA6UmLQUBrRc795UhHybhfmZNoMP6yrNVrXyKfXZP7GSW3vjyBRzFZkdtPMftGXwhdjM9KNtkckHp87JeDTDsbTsyULKhwoa58aCikCGz

Bitcoin (BTC)
Address: xpub6DCReLAAeuckXmiv9iGxEBGbmmPj5s5FC7cMxncaSgb5JLh4zbzLsNshDWLrq3tr1QPXFPokMk5aM4crxintpatA32GsjC1NXprGX2vz727
